### ISSUE TITLE
Provide LGPL exclusion license

### ISSUE THREAD

**Issue by FatBrownDog** [bluetiger9/SmtpClient-for-Qt#145]
Hi,
What is the cost or price for licensing this project under non-GPL?

For example, like some authors such clause:
https://github.com/fnc12/sqlite_orm
"The project has AGPL license for open source project and MIT license after purchasing it for 50$"

**Comment by attila-tokes** [comment]
@FatBrownDog, what would you do with a MIT licensed version of the library? If you want to use the library in a commercial product, the LGPL license already allows it.

**Comment by ghost** [comment]
I do static linking, (increase speed, increase performance), fix bugs and make modifications without contribute back.

**Comment by ghost** [comment]
At the moment, I'm using Libcurl... it's clunky and works slowly. I'm looking at a static linked solution.

**Comment by attila-tokes** [comment]
I don't think using static linking will make the library any faster. The speed of sending a mail over SMTP is essentially limited by the network speed.

What you are proposing would need a commercial license _(not MIT)_. The library is already usable in commercial products, and I prefer keeping the LGPL license, so that improvements are contributed back to the project.

Thanks!
