### ISSUE TITLE
Error Import

### ISSUE THREAD

**Issue by BL-Bl4ckBut7ch3r** [bluetiger9/SmtpClient-for-Qt#148]
Hi!

I'm facing with an issues where I would use these source and header files but I receive import error upon compilation. (ex:undefined reference to `__imp__ZN11MimeMessageD1Ev')

I'm trying this on QT creator 4.11.1 and QT 5.14.2

I have the same setup on a raspberry Pi where on the QT (same versions) works just fine. Any ideas of why does this happen?

**Comment by bluetiger9** [comment]
@BL-Bl4ckBut7ch3r, did you compiled the shared library and your application with the same Qt version and compiler?

**Comment by bartaandras** [comment]
I have the same issue when I try to use it as a static lib in windows. On linux it works fine but on windows it gives undefined references. I have Qt 6.2.3 MINGW-64.
The SmtpEmail project builds fine and the static library (.a) is created. The issue happens when I try to link it to the rest of the project. It works fine even in windows if I build it as a dll.

Is it possible to use it as a static lib in windows?

**Comment by bluetiger9** [comment]
@bartaandras, the library isn't really meant to be compiled as a static library. It may work, but you need to figure it yourself what goes wrong.
