### ISSUE TITLE
Newlines aren't sent

### ISSUE THREAD

**Issue by aiphae** [bluetiger9/SmtpClient-for-Qt#161]
When adding text with newline characters (\n) to the message, they don't actually make new lines in the sent email.

I tried replacing them with `<br />` and other stuff but without success.

```
MimeText *text = new MimeText();
text->setText(email.getBody());
message.addPart(text);
```

**Comment by mozhongzhou** [comment]
自动回复：已收到您的邮件

**Comment by bluetiger9** [comment]
Hi! :slightly_smiling_face: 

Using newlines (`\n`) with `MimeText` should work fine. You can take a look at [demo1.cpp](https://github.com/bluetiger9/SmtpClient-for-Qt/blob/v2.0/demos/demo1/demo1.cpp#L29) for a working example.

If this does not works with a particular email provider, I would try two things:
1. Use win style newlines (`\r\n`)
2. Switch to HTML content. For this use `MimeHtml` instead of `MimeText`. See [demo4.cpp](https://github.com/bluetiger9/SmtpClient-for-Qt/blob/v2.0/demos/demo4/demo4.cpp#L41) for more details.

Thanks!
