### ISSUE TITLE
How to install this to Visual Sudio QT project

### ISSUE THREAD

**Issue by bfilipiuk** [bluetiger9/SmtpClient-for-Qt#169]
Hello everyone,
I'm creating Qt project in Visual Studio and I struggle with implementing this library to my project. I've tried different ways to compile and link it but every way I try is leading to tons of errors and some features seems unavailable in VS (?). I feel like I'm missing something obvious.

Please note that I'm a beginner at installing custom C++ libs and I might need bit more specific (maybe step-by-step) walkthrough about installing this in a correct way.

**Comment by mozhongzhou** [comment]
自动回复：已收到您的邮件

**Comment by bluetiger9** [comment]
@bfilipiuk, never compiled the library in Visual Studio, but as far I remember other people succeeded with it.

According to ChatGPT you can go with one of two approaches:
1. Import the project from the Qt `.pro` file.
2. Import the project as a CMake project.

Both seems to need some configuration in order to set the QT paths and other stuff. 

I would suggest trying to set up Visual Studio with a simple project Qt first, then you can see if any changes are needed in the `.pro` or `CMakeLists.txt` in order to compile the library.

Btw, the library is supposed to be compiled to a shared library (DLL in windows). Then you should link the resulting library to your project.

**Comment by bfilipiuk** [comment]
Could you tell me which prompt have you used to get those info?

**Comment by bluetiger9** [comment]
Sure. Here it is:
https://chatgpt.com/share/67155121-91c8-8003-bfe0-a446dccf6c82

**Comment by bfilipiuk** [comment]
Thank you, I managed to implement it. What worked for me was building it via Qt terminal with specific compiler and then linking it to VS. lib straight to project and dll to PATH environment variable.
