### ISSUE TITLE
Doesn't work with Android 7.0

### ISSUE THREAD

**Issue by tiagojanz** [bluetiger9/SmtpClient-for-Qt#55]
Hi,

Is it possible to use boringssl instead?

**Comment by bluetiger9** [comment]
Never tried the library with Android. What exactly goes wrong?

**Comment by correa** [comment]
The library uses SSL from Qt, So if there is a problem regarding SSL on Android it should be reported to Qt on bugreports.qt.io

**Comment by vinaykulkarni89** [comment]
Android does not allow OpenSSL as inbuilt from 7.0
You have to add the OpenSSL library to application manually for android

**Comment by bluetiger9** [comment]
The problem seems to be that the OpenSSL is no longer built into the Android since version 7.0. The problem and it's possible solutions are discussed in more detail in different places. Some of them are:
- [StackOverflow post - QT + OpenSSL + Android](https://stackoverflow.com/a/43342447/1048255)
- [Official Qt 5.10 documentation page about OpenSSL on Android](http://doc.qt.io/qt-5/opensslsupport.html)
- [Qt Forum topic - How to create openssl library for Android?](https://forum.qt.io/topic/75615/how-to-create-openssl-library-for-android)

According to these the problem can be solved by packing the OpenSSL library into the APK.

I'm closing this issue for now. Please use the above references for more information. Thanks!
